In [3]:
print("Hello World!")

Hello World!


In [4]:
# Start Numpy
import numpy as np

In [5]:
data = [1,2,3,4,5] # Data list
data

[1, 2, 3, 4, 5]

In [6]:
np.array(data) # Mengubah list menjadi numpy array

array([1, 2, 3, 4, 5])

In [7]:
np.arange(0,10) # Membuat data array numpy secara otomatis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2) # argumen ketiga (nilai = 2) merupakan kelipatan

array([0, 2, 4, 6, 8])

In [9]:
# Membuat array dummy
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,10,50) # Membuat data array 0 sampai 10 sebanyak 50 buah

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
# Membuat array secara random
np.random.rand(3) # nilai random (hanya positif)

array([0.63865138, 0.59700002, 0.45498582])

In [12]:
np.random.rand(5,7)

array([[0.31709071, 0.37968995, 0.47809592, 0.36290583, 0.76508101,
        0.36049789, 0.56059195],
       [0.02443889, 0.6077325 , 0.39532585, 0.52732848, 0.9475113 ,
        0.16226964, 0.65480888],
       [0.37417681, 0.48128359, 0.82512846, 0.10080559, 0.92210135,
        0.57772141, 0.57905791],
       [0.35171972, 0.32619319, 0.17514564, 0.31137463, 0.55205518,
        0.10621147, 0.76338589],
       [0.98435056, 0.14160036, 0.45679943, 0.85609378, 0.78094645,
        0.68323414, 0.00207581]])

In [13]:
# Membuat data array random secara negatif dan positif
np.random.randn(5,5) # ada nilai positif dan negatif

array([[-0.28450583, -2.07597239, -0.14346766, -0.71925014,  0.4290347 ],
       [-1.37143951, -0.26923056,  1.83742099, -0.11100726, -1.23846435],
       [ 0.94889757,  0.05504594, -0.36616997, -0.59988113, -0.0571762 ],
       [ 1.81319345, -2.33755949,  1.00426865,  1.29373125,  0.49754383],
       [-0.10414336,  1.06736343,  0.26883067,  0.40625018, -1.00790673]])

In [14]:
#Membuat data array random bilangan bulat
np.random.randint(1,50)

40

In [15]:
np.random.randint(1,50,10)

array([38, 35, 35,  1,  4, 48, 33, 48, 16, 45])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5,5) # Mengubah tampilan array dari 1D menjadi 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr.max() # Nilai array terbesar

24

In [20]:
arr.min() # Nilai array terkecil

0

In [21]:
arr.argmax() # Indeks nilai terbesar

24

In [22]:
arr.argmin() # Indeks nilai terkecil

0

In [23]:
arr.sum() # Menjumlahkan semua array


300

In [24]:
arr.sum() - arr.max()

276

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])