In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[8]  # mendapatkan nilai dari sebuah index array

8

In [4]:
arr[0:3]  # mendapatkan nilai dari jarak index

array([0, 1, 2])

In [5]:
arr[0] = 9  # mengubah data array numpy

In [6]:
arr


array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[0:5] = 9  # mengubah nilai dari index 0 sampai SEBELUM 5

In [8]:
arr

array([9, 9, 9, 9, 9, 5, 6, 7, 8, 9])

In [9]:
data = arr[0:5]

In [10]:
data

array([9, 9, 9, 9, 9])

In [11]:
data[:] = 99  # mengubah SEMUA data array

In [12]:
data

array([99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [14]:
newData = arr.copy()  # menduplikasi suatu data pada numpy agar dapat diubah datanya

In [15]:
newData

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [17]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[2]  # menampilkan array 2D index ke 2

array([35, 40, 45])

In [22]:
arr_2d[2][1]  # menampilkan array 2D index ke 2, kolom 1

40

In [23]:
arr_2d[1][2]  # menampilkan array 2D index ke 1, kolom 2

30

In [26]:
arr_2d[0:2,1:3]  
# menampilkan array berdasarkan rangenya:
# 0:2 berarti menampilkan index 0 sampai dengan index dibawah 2
# 1:3 berarti menampilkan kolom 1 sampai dengan kolom dibawah 3

array([[10, 15],
       [25, 30]])

In [25]:
arr_2d[:2,1:]
# :2 berarti menampilkan index yang di bawah dari index 2, berarti index 0 dan 1
# 1: berarti menampilkan kolom 1 atau yang di atas dari kolom 1, berarti kolom 2

array([[10, 15],
       [25, 30]])

In [27]:
 nilai = np.arange(1,11)

In [28]:
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
nilai > 5  # menseleksi data array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
nilai[nilai > 5]  # menseleksi data array

array([ 6,  7,  8,  9, 10])

In [32]:
nilai + nilai

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
nilai * nilai

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
nilai / nilai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
nilai - nilai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])