In [4]:
print("Hello World!")

Hello World!


In [5]:
# Start Numpy
import numpy as np

In [6]:
data = [1,2,3,4,5] # Data list
data

[1, 2, 3, 4, 5]

In [7]:
np.array(data) # Mengubah list menjadi numpy array

array([1, 2, 3, 4, 5])

In [8]:
np.arange(0,10) # Membuat data array numpy secara otomatis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2) # argumen ketiga (nilai = 2) merupakan kelipatan

array([0, 2, 4, 6, 8])

In [10]:
# Membuat array dummy
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50) # Membuat data array 0 sampai 10 sebanyak 50 buah

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
# Membuat array secara random
np.random.rand(3) # nilai random (hanya positif)

array([0.09017315, 0.57589494, 0.19313789])

In [13]:
np.random.rand(5,7)

array([[0.29589891, 0.98384448, 0.85181439, 0.19239555, 0.36626847,
        0.7562312 , 0.15164458],
       [0.0910959 , 0.16956362, 0.34801483, 0.56053511, 0.39059329,
        0.68583381, 0.24675483],
       [0.40582352, 0.04575381, 0.29692355, 0.25591371, 0.41454332,
        0.07088694, 0.38128365],
       [0.49184784, 0.06604696, 0.4328029 , 0.66552413, 0.17218887,
        0.71632391, 0.70131562],
       [0.86250981, 0.23084814, 0.45633942, 0.5885888 , 0.7287242 ,
        0.45626119, 0.93303416]])

In [14]:
# Membuat data array random secara negatif dan positif
np.random.randn(5,5) # ada nilai positif dan negatif

array([[-0.58568391, -1.48213193, -1.32195064,  2.35271008, -0.12510974],
       [ 1.26968752,  0.40470957, -0.35212849, -0.41811736,  1.41310833],
       [ 1.63282639, -1.06184573, -0.77403563, -0.37010527, -0.42741217],
       [ 0.39727363,  0.17813461,  2.23365132,  1.10070578, -2.51013615],
       [-0.57552505, -0.33163717,  1.95559112, -0.62944957,  1.36839306]])

In [15]:
#Membuat data array random bilangan bulat
np.random.randint(1,50)

47

In [16]:
np.random.randint(1,50,10)

array([15,  3, 23, 34, 24, 12,  6, 33,  2, 16])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5) # Mengubah tampilan array dari 1D menjadi 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.max() # Nilai array terbesar

24

In [24]:
arr.min() # Nilai array terkecil

0

In [25]:
arr.argmax() # Indeks nilai terbesar

24

In [26]:
arr.argmin() # Indeks nilai terkecil

0

In [31]:
arr.sum() # Menjumlahkan semua array


300

In [20]:
arr.sum() - arr.max()

276